### ISSUE TITLE
Base Var Name Suggestions

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#1]
[On the base var file](https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/core/base/_vars.scss), the vars relating to block spacing could be renamed to be consistent, as well as use the size indicator.

Right now we do not have any addition spacing beyond the large size, but this naming convention gives us the flexibility to easily add one in the future.

Current code:
```
// 2. Margins/spacing
// ------------------
$margin-bottom: 30px;

// Side padding use on small screen
$mobile-padding: 25px;

// Bottom margin used on all blocks
$block-margin-bottom: 40px !default;

$block-padding: 40px;
```

Suggested change:
```
// 2. Margins/spacing
// ------------------
$margin-bottom: 30px;

// Block Spacing
$block-margin-bottom: 40px !default;
$block-padding-s: 25px;
$block-padding-m: 40px;
```

**Comment by dannybrown73** [comment]
Cool. yes, will make this change.

**Comment by dannybrown73** [comment]
Done.
