### ISSUE TITLE
Footer blocks

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#12]
### Sitemap Footer1

Using the latest footer pen, [b-footer-0.0.2](https://codepen.io/cuweb/pen/BPREvW) grab the sass and markup for footer-sitemap.

### Simple Footer

Also important to note that there has been minor update to the simple footer markup, mainly it was missing `u-block-full` at the `u-block-row-black` level, and the `b-footer-simple` class name was move up a level to be consistent with how the other footer blocks are done.

Update to existing scss file: https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/blocks/footer/footer-simple.scss

Currently line 6 has `padding-bottom: 25px;`, change it to `40px`

The 40px spacing matches spacing used between all other block level elements.

**Comment by dannybrown73** [comment]
Ok. This is all done. @troychaplin79 I updated the HTML in the sitemap footer block. You can see at https://dannybrown73.github.io/rds-docs/docs/blocks/footer/sitemap/

If you want to update the codepen its up to you. Small changes included:

changed all http links to https and added aome aria hidden tags to the svgs along with a text replacement for ravens icon.
