### ISSUE TITLE
Layouts break without block elements in them.

### ISSUE THREAD

**Issue by dannybrown73** [dannybrown73/rds-docs#13]
**Bug**

**EDIT**
Actually, upon review. It looks to be an issue when there isn't enough content.

The fix is to add a 100% width to the b-content. Looking for feedback on whether we should add this to u-block?

**old comment**

It looks like we only ever tested our layouts with display: block content in them. With only inline elements in the <main> column, the block doesn't take its full width and looks centered.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://codepen.io/cuweb/pen/GGwyzM?editors=1010
2. Notice how using an inline element

**Expected behaviour**
How it looks if there is a block item like `<h2>` in the content block.

**Desktop**
 - Chrome

**Smartphone**
 - Didn't check

**Comment by troychaplin79** [comment]
```
.u-block {
	width: 100%;
}
```

**Comment by dannybrown73** [comment]
Fixed: added width 100% to `u-block` and uploaded `core-0.1.18`.
