### ISSUE TITLE
Update Listing Group block

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#14]
New pen for block is here: https://codepen.io/cuweb/pen/PBeQgX

All classes were prefixed with `new-` to avoid conflict, those should be removed after @dannybrown73 is finished a review, and any further changes, then this will replace the entirety of the existing markup and css for the block

**Comment by troychaplin79** [comment]
@dannybrown73 styles reviewed and updated, ready to be updated in core

**Comment by dannybrown73** [comment]
Done added in core core 0.1.22
