### ISSUE TITLE
Img, Audio, Video base styles

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#2]
[On this sass file](https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/core/base/_base.scss)

Styles are different on img than on video, so it doesn't make sense to keep a shared style here. Image uses a max-width, video uses width, and we have not dealt with audio embeds yet.

Remove the following from base when updating with final version of b-content:

```
img,
video,
audio {
    max-width: 100%;
    height: auto;
}
```

**Comment by dannybrown73** [comment]
Done.
