### ISSUE TITLE
Update card component in docs

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#23]
This file: https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/components/cards/_card.scss

Replace all the content with the css from this pen: https://codepen.io/cuweb/pen/rryPKO

**Comment by dannybrown73** [comment]
Done. But haven't adjusted HTML in docs so gonna keep open and adjust issue title.

**Comment by troychaplin79** [comment]
@dannybrown73 noted and linked up in new repo and can be closed here if you want: https://github.com/ravendesignsystem/rds/issues/4
