### ISSUE TITLE
Video / Audio styles updates

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#35]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/_base.scss

Either before or after `video` on line 168, add the following:

```
audio {
	width: 100%;
	margin-bottom: 20px;
}
```

**Note:** width is optional, based on personal preference. I like it full width, but maybe you do not @dannybrown73 

For HTML5 videos, phones do not render video until you hit play button, so it looked broken. Adding a background color here helps with that:

```
video {
	width: 100%;
	margin-bottom: 20px;
	height: auto;
	background-color: $grey-luke;
}
```

Example of the styles can be seen: https://s.codepen.io/cuweb/debug/VBGoLx

**Comment by dannybrown73** [comment]
Agree 100% looks good. Updated. Included in core 0.1.21.
