### ISSUE TITLE
Images with Caption IE11 fix

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#36]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/components/content/_img-caption.scss

There was a bug, only in IE11, where if an image with a caption was wider than the set content area, regardless of any width properties added to the markup, it broke outside the content area. I added a media query that only targets IE11, so nothing else is impacted by this, and set a max-width equal to the content area itself (for some reason, max-width 100% does nothing, has to be a set px width)

Fix can be seen / tested here: https://s.codepen.io/cuweb/debug/VBGoLx

There were a couple other minor changes not related to IE11 bug, so replace all styles with:

```
.c-content-img-caption {
    display: table;
	margin-bottom: 20px;

    img {
        margin-bottom: 0 !important;
		
		// Fixes image width when larger than content area
		@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
			max-width: #{map-get($breakpoints, s)};
		}
    }
}

.img-caption__text {
    display: table-caption;
    caption-side: bottom;
    background: $grey;
    padding: 20px !important; // important forces override of last-child on u-block:p
    font-size: 14px;
    font-style: italic;
    line-height: 1.4;
}
```

**Comment by dannybrown73** [comment]
Updated. Included in core 0.1.21.
