### ISSUE TITLE
Update base styles

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#40]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/_base.scss
and
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/blocks/content/_content.scss
and
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/components/content/_img-caption.scss

Update all 3 scss files referenced in this pen: https://codepen.io/cuweb/pen/vaQEyj

**Comment by troychaplin79** [comment]
@dannybrown73 the table update has been put into [b-content-1.0.0](https://codepen.io/cuweb/pen/pZxMZb) and the styles have been commented out

**Comment by troychaplin79** [comment]
@dannybrown73 final pen reviewed and ready to be added back to core

**Comment by dannybrown73** [comment]
All added... v1.0.0 good to go.
