### ISSUE TITLE
Footer Updates

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#41]
3 individual scss files need updating, URLs to each file are noted in the latest pen: https://codepen.io/cuweb/pen/gjxdVp

Style updates were in regards to below small size, the cu logo and social icons were far to large IMO (logo was nearly 95% of the overall width) and social icons for one of the 2 footer types were float dropping (they are now matched up in size, all on one line)

Markup also changed, there were a bunch of error from link checking, most existed in the sitemap version, but might as well update all 3 (branding, sitemap, simple)

Also, sitemap footer isn't using any h-card stuff for address and other contact info. I'm at a loss on this one, hoping that you know/understand it better.

**Comment by troychaplin79** [comment]
@dannybrown73 final pen reviewed and ready to be added back to core

**Comment by dannybrown73** [comment]
Updated in core 0.1.22
