### ISSUE TITLE
Card Updates

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#42]
https://codepen.io/cuweb/pen/MBXKwO

Video cards have an icon that needs the aria hidden portion changed. Currently it's written as:

```
<span class="card__icon c-icon-play-button--white u-icon-bg u-icon-bg--overlay" title="Video" aria-hidden></span>
```

It should be written as:

```
<span class="card__icon c-icon-play-button--white u-icon-bg u-icon-bg--overlay" title="Video" aria-hidden="true"></span>
```

`aria-hidden` was changed to `aria-hidden="true"`

**Comment by troychaplin79** [comment]
@dannybrown73 final pen reviewed and ready to be added back to core

**Comment by dannybrown73** [comment]
Updated and labelled 1.00
