### ISSUE TITLE
File outside directory

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#46]
https://github.com/dannybrown73/rds-docs/tree/master/src/_scss/rds/components

`_badges.scss` and `_icons.scss` are at the root of the components folder, this is different than the standard way of organizing everything else.

If changing path, they are referenced on lines 80 and 88 here: https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/core.scss

**Comment by dannybrown73** [comment]
K...this is cleaned up.
