### ISSUE TITLE
Addition to banner styles

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#48]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/blocks/banners/_banner.scss

When a banner, without an image, is used, and is immediately followed by a grey block, there's a decent amount of extra space, which can be seen by commenting out the banner styles on this pen: https://codepen.io/cuweb/pen/EpMeGj

Recommendation, add the following to banner scss file noted above:

```
// When grey block is used after banner that does not use img bg, tighten up the space between them
// ====================================

.b-banners-banner:not(.b-banners-banner--img) + .u-block-row-grey {
	margin-top: -80px;
}
```

**Comment by troychaplin79** [comment]
@dannybrown73 reviewed and ready to add to core

**Comment by dannybrown73** [comment]
Done. Added with core 0.1.22.
