### ISSUE TITLE
Grid Height for IE11

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#5]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/_utilities.scss

Line 42: `display: flex;`
Line 43: `flex-direction: column; // helps with equal height`

This causes odd height issues on grid items in IE11, removing both fixes everything. I understand why this is being done, but I don't think it should be forced on every flex-item, but rather, done on a case-by-case basis when needed.

**Comment by dannybrown73** [comment]
Fixed and pushed. Closing issue.
