### ISSUE TITLE
Updated search block

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#54]
https://codepen.io/cuweb/pen/eLGyKP

Updated markup to reflect the new b-header-search block, as well as 1 item that is required in css to tighten up space when search block is used above or below the banner block

**Comment by dannybrown73** [comment]
This block is available in core 0.2.0 on the new CDN for distributions moving forward: http://cu-rds.s3.amazonaws.com/rds/0.2.0/rds-core-min.css

Didn't end up using the markup above. The extra padding still exists for grey rows after banner but a solution will be implemented in another ticket.

This isn't documented yet but we have another ticket for that, so you can close this if all works for you.

**Comment by troychaplin79** [comment]
This is working just fine in FF build, any spacing issue mentioned have been worked out with most recent u-block solution
