### ISSUE TITLE
Role on banner

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#57]
Before the changes to remove u-block-ful, the main banner wrapper had role="banner" on them, was that just an oversight when you were making the updates?

**Comment by dannybrown73** [comment]
Good looking out but I dug into more and realized I was using that tag inappropriately as it shopuld be a top-level landmark. So I added it to the header when appropriate. Ref: https://www.w3.org/TR/wai-aria-practices/examples/landmarks/banner.html
