### ISSUE TITLE
New Var

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#63]
I think we should add a var for the font-family. There are cases where the browser ignores what we currently have set in _base.scss

NOTE: if you add the new var, update the font-family reference here: https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/elements/_base.scss

I'm suggesting we add:

`$font-family: "Gotham Narrow SSm A", "Gotham Narrow SSm B", -apple-system, blinkmacsystemfont, "Segoe UI", "Roboto", "Helvetica Neue", "Helvetica", "Arial", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`

Or maybe a more simplified version:

`$font-family: "Gotham Narrow SSm A", "Gotham Narrow SSm B", "Helvetica Neue", "Helvetica", "Arial", sans-serif;`

**Comment by dannybrown73** [comment]
@troychaplin79 I added the var and started a new area on CDN for the var files 
http://cu-rds.s3.amazonaws.com/scss/vars/0.1.0/_vars.scs s but can you point out what is different and why the _base.scss file needs updating

**Comment by troychaplin79** [comment]
@dannybrown73 it made sense to update the font family in base if we now have a var for it. Probably won’t happen, but if we update the var we might forget the base one if it doesn’t use the var

**Comment by dannybrown73** [comment]
Oh ahh I get it now... use the var in the base file. Sure make sense.  I was looking at your proposed stack fro what was different. Ok, i've add the variable to the base font stack.
