### ISSUE TITLE
Grey block bg

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#64]
On u-block--grey we use #eee, but b-header-banner uses #f3f3f3... I'm guessing that this was either an oversight, or perhaps by design? If by design, then reducing the space between banner and either search of meta that could immediately follow it.

There will be an example of this on devsite.carleton.ca/futurefunder shortly, I will make a comment when I've finished updating and push it to the server.

**Comment by dannybrown73** [comment]
Fixed to use proper var.
