### ISSUE TITLE
RDS Doc Style Broken

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#66]
Something messed up during your last compile / commit / auto deploy to git cuz https://devsite.carleton.ca/futurefunder/2018/09/project-sample/ is broken

**Comment by troychaplin79** [comment]
@dannybrown73 looks like it's the call to the app.css that's the issue, it's trying to call it from your localhost, so my guess is that when you look at the docs, there's no problem

**Comment by dannybrown73** [comment]
Fixed.
