### ISSUE TITLE
Banner change

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#67]
on `b-header-banner` there's `justify-content: center` and `align-items: center`

The align-items won't do anything here, it's a property used for flex items, which the banner block is not.

For some reason, having justify content center there breaks the layout for IE11, as see in the screenshot. I removed it via the inspector in IE11, Edge, and on the Mac, Safari, Chrome and Firefox, and each of them works as expected.

Recommendation: remove `justify-content: center` and `align-items: center` on `b-header-banner`

**Comment by troychaplin79** [comment]
<img width="1978" alt="screen shot 2018-09-13 at 1 15 23 pm" src="https://user-images.githubusercontent.com/15524465/45505128-c7641f00-b759-11e8-88b4-688fd751bd56.png">

**Comment by dannybrown73** [comment]
I took out align-items: center as it did nothing but removing justify-content: center; broke the centering. We need to dig into this a bit more.

**Comment by troychaplin79** [comment]
@dannybrown73 ok, i'll look into that today or tomorrow morning

**Comment by troychaplin79** [comment]
Closing this, all fixed with new u-block stuff
