### ISSUE TITLE
Banner Breadcrumbs

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#68]
When using yoast, the last breadcrumb is being displayed. In the docs, the last breadcrumb has `u-visually-hidden` applied to it.

We can deal with the yoast stuff in one of 2 ways:

1. On `u-visually-hidden` that exists [in this file on line 556](https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/utilities/_utilities.scss), we add the `.breadcrumb_last` class so it shares those styles.

2. In the [banner scss file](https://github.com/dannybrown73/rds-docs/blob/master/src/_blocks/header/banner/_banner.scss) we add:

```
.breadcrumb_last {
	display: none;
}
```

**Comment by dannybrown73** [comment]
@troychaplin79  Are you able to explain why u-visually-hidden is ignored when Yoast is used?

**Comment by troychaplin79** [comment]
@dannybrown73 it’s not ignored, it just doesn’t exist, yoast wraps last breadcrumb item with a span and uses the class as mention above

**Comment by dannybrown73** [comment]
Ok. Got it. So next question, based on trying to keep things vanilla and no custom styling...my next question is do we need Yoast to do breadcrumbs. I realize it's been a standard of ours for a while but is it worthwhile to look at custom breadcrumbs in WP, grabbing parent and child with base functions? Too complicated to bother with or is their value? tag @troychaplin79

**Comment by troychaplin79** [comment]
@dannybrown73 I can't see it being too hard, I [found this just now](https://torquemag.io/2017/10/add-breadcrumbs-wordpress-website/), method #2 is for custom crumbs, there could be better options though.

I figured for now, time constraints leads me to think why not just use yoast if the plugin is active anyway.

**Comment by dannybrown73** [comment]
Did number 2 - added to banner.scss
