### ISSUE TITLE
Odd break point

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#70]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/utilities/_utilities.scss

Lines 38-41:

```
// TODO: this needs more testing, Troy saw some odd results
@include media(">=870px") {
	width: 25%;
}
```

Not sure what we were trying to do, but this causes issues with grid breakpoints. I wanna say this was an idea we had to change the breakpoint for 4 column grid items (mainly on cards) so they would break earlier... If that's the case, we should do this specifically on `u-grid--4` and leave the stuff noted above at the `s` breakpoint

**Comment by dannybrown73** [comment]
Adjusted, to only be on u-grid-4. But we'll need to update the docs because the default u-grid was the 4 column grid.

**Comment by dannybrown73** [comment]
Closing.

**Comment by dannybrown73** [comment]
Actually...going to reopen for @troychaplin79 to test. Close if this works.

**Comment by troychaplin79** [comment]
Works fine, logged a new ticket in new repo to continue a related discussion
