### ISSUE TITLE
Block / Row spacing

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#71]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/utilities/_utilities.scss

Lines 140-146.

New code:

```
.u-block-full--grey + .u-block-full--grey,
.u-block-full--black:not(.b-footer-cu-contact) + .u-block-full--black,
.u-row + .u-row,
.u-row + .u-block-full--grey,
.u-block-full--grey:not(.b-header-banner--img) + .u-row {
	margin-top: -$block-margin * 2;
}
```

When banner image is used, we don't wanna reduce the space with next item if used, as it butts it up directly to the image... Adding `:not(.b-header-banner--img)` prevents this from happening.

In the sitemap footer, space between `b-footer-cu-contact` and branding is removed, we can avoid this by adding `:not(.b-footer-cu-contact)` as noted above

**Comment by troychaplin79** [comment]
@dannybrown73 of course, we could force margin on each specific class noted above, but i think because these are consistently used global classes, this is the best way to do it, instead of adding a couple `important` tags

**Comment by dannybrown73** [comment]
@troychaplin79 we need to discuss this one in person. I can't follow. Hard to figure out without example links.

**Comment by dannybrown73** [comment]
When I add a `u-block-full u-block-full--grey` after a photo, it seems to work ok. A link would help me figure this one out.
