### ISSUE TITLE
Last item spacing

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#72]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/utilities/_utilities.scss

Line 159-164

New code:

```
main .u-block-full--grey:last-of-type,
main .u-block-full--black:last-of-type,
main .u-row:last-of-type,
footer .u-block-full--grey:last-of-type,
footer .u-block-full--black:last-of-type {
	margin-bottom: 0;
}
```

Adding `main .u-row:last-of-type` removes space between the last u-row and the footer

**Comment by dannybrown73** [comment]
Added.
