### ISSUE TITLE
Banner Carousel

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#73]
https://github.com/dannybrown73/rds-docs/blob/master/src/_blocks/header/masthead/_masthead.scss

Line 23-25update to look like:

```
& ~ .b-header-banner,
& ~ .tns-outer {
	margin-top: 78px !important; // avoid the jumping from the loss of masthead height when made position fixed.
}
```

Adding `.tns-outer` covers carousel banners, this is the class automatically added by tiny-slider, wrapping the entire slideshow

**Comment by dannybrown73** [comment]
Added.
