### ISSUE TITLE
Last u-block in page layouts

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#77]
https://github.com/dannybrown73/rds-docs/blob/master/src/_layouts/body/_layouts.scss

When u-block is used in page layout, there's a 40px margin at the bottom of the last child. The divider line between aside and content area going 40px further down the page than the content looks bad, so I'm suggesting the followin change to reduce that space in half.

An example of the proposed space reduction can be found here: https://devsite.carleton.ca/futurefunder/project-listing/

Line 91-99

```
.body__content {
	overflow: hidden;
	width: 100%;

	// remove empty p tags caused by markdown and editors
	p:empty {
		display: none;
	}

	.u-block:last-child {
		margin-bottom: $block-margin / 2;
	}
}
```

**Comment by dannybrown73** [comment]
Added.
