### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#78]
https://github.com/dannybrown73/rds-docs/blob/master/src/_scss/rds/base/elements/_base.scss

Line 214 --> `max-width: min-content; // used to force responsive`

Having this one rule in place causes issue with any table that is generated by ACF in a front end editing setup. This is doing nothing, and has next to no support (https://caniuse.com/#feat=intrinsic-width).

We should remove it. I tested it on all browsers (include IE and Edge) without it, and I can't see a difference.

**Comment by dannybrown73** [comment]
Removed.
