### ISSUE TITLE
ADD Component: Search Form  to docs

### ISSUE THREAD

**Issue by troychaplin79** [dannybrown73/rds-docs#8]
Example of the search component can be found: 
https://codepen.io/cuweb/pen/EpNZGJ

Note: in the css area I've added an item that reduces spacing between banners and search form, as without it I find it's way too much. You may wanna play with it to be sure you're happy with the spacing. That bit of css is as follows:

```
.b-banners-banner:not(.b-banners-banner--img) + .u-block-row-grey {
	margin-top: -80px;
}
```

**Comment by troychaplin79** [comment]
@dannybrown73 link fixed

**Comment by dannybrown73** [comment]
Added HTML and SCSS to core. Still, need to add to Docs. Updating the ticket title.

Latest pen: https://codepen.io/cuweb/pen/PBygev

**Comment by troychaplin79** [comment]
@dannybrown73 noted and linked up in new repo and can be closed here if you want: https://github.com/ravendesignsystem/rds/issues/4
